name: Run tests
on: [repository_dispatch]

jobs:
  check-github-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check timestamp
        run: |
          python3 check_timestamp.py ${{ github.event.client_payload.commit_timestamp }}
